logging:
  level:
    com:
      mycompany:
        myapp: INFO
spring:
  application:
    name: JhipsterSampleApplication
  jackson:
    default-property-inclusion: non_absent
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/jhipsterSampleApplication
    username: jhipsterSampleApplication
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
application:
  security:
    jwt-base64-secret: YzEzNzdhMWMxYjM3OTkyZWFiYzA4MjRkYjJkNWQxNTYzM2ZhOWEyYzMzNzI0YzI4MzNlOWM0NzYzZTI4M2I5NA==
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - threaddump
